### ISSUE TITLE
stats page still having issues?  

### ISSUE THREAD

**Issue by gbinal** [dlapiduz/govcode.org#38]
https://www.govcode.org/stats

![screen shot 2015-01-29 at 8 01 48 pm](https://cloud.githubusercontent.com/assets/633088/5969435/c17d77c4-a7f1-11e4-9977-1f15f59c30a8.png)

**Comment by alex** [comment]
Exception from the console (appears 2x):

```
 TypeError: Cannot read property 'datasets' of undefined
    at Object.b.Type.extend.initialize (https://www.govcode.org/scripts/vendor.1b7a7c81.js:4:91074)
    at Object.c.Type (https://www.govcode.org/scripts/vendor.1b7a7c81.js:4:73170)
    at Object.c.Type.extend.d (https://www.govcode.org/scripts/vendor.1b7a7c81.js:4:76502)
    at c.Type.extend.c.(anonymous function) [as Bar] (https://www.govcode.org/scripts/vendor.1b7a7c81.js:4:76844)
    at a.factory.undefined.a.link (https://www.govcode.org/scripts/vendor.1b7a7c81.js:5:17815)
    at https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:36020
    at s (https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:30567)
    at h (https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:26605)
    at h (https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:26622)
    at h (https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:26622) <canvas dataset="countGraphData" options="countGraphOptions" autofit="true" class="ng-isolate-scope" height="150" width="300" style="width: 300px; height: 150px;">
```

**Comment by dlapiduz** [comment]
@gbinal thanks for sending this. I need to figure out a long term solution for this. It keeps having issues :s
