### ISSUE TITLE
Stats page is not working

### ISSUE THREAD

**Issue by dlapiduz** [dlapiduz/govcode.org#48]
For a long time the stats page has been causing some front end headaches.

The data is there from the API but there is some issue with Charts.js.

The url is https://www.govcode.org/stats

**Comment by msecret** [comment]
Here is a JS error:

**Comment by msecret** [comment]
```js
TypeError: Cannot read property 'datasets' of undefined
    at Object.b.Type.extend.initialize (https://www.govcode.org/scripts/vendor.1b7a7c81.js:4:91074)
    at Object.c.Type (https://www.govcode.org/scripts/vendor.1b7a7c81.js:4:73170)
    at Object.d (https://www.govcode.org/scripts/vendor.1b7a7c81.js:4:76502)
    at c.(anonymous function) [as Bar] (https://www.govcode.org/scripts/vendor.1b7a7c81.js:4:76844)
    at undefined.a.link (https://www.govcode.org/scripts/vendor.1b7a7c81.js:5:17815)
    at https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:36020
    at s (https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:30567)
    at h (https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:26605)
    at h (https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:26622)
    at h (https://www.govcode.org/scripts/vendor.1b7a7c81.js:2:26622) <canvas dataset="countGraphData" options="countGraphOptions" autofit="true" class="ng-isolate-scope" height="300" width="600" style="width: 300px; height: 150px;">vendor.1b7a7c81.js:2 (anonymous function)```
